import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Manrope,
  PT_Sans,
  PT_Sans_Caption,
} from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/footer";
import SubNavigation from "@/components/header/utility-navigation";
import PrimaryNavigation from "@/components/header/main-navigation";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const ptSans = PT_Sans({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-pt-sans",
});

const ptSansCaptions = PT_Sans_Caption({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pt-sans-caption",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${ptSans.variable} ${manrope.variable} ${ptSansCaptions.variable}  antialiased`}
      >
        <SubNavigation />
        <PrimaryNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
